/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FileType = { 'pdf' : null } |
  { 'text' : null };
export interface Internship {
  'id' : InternshipId,
  'duration' : string,
  'postedDate' : Timestamp,
  'role' : string,
  'description' : string,
  'deadline' : string,
  'isActive' : boolean,
  'company' : string,
  'pdfKey' : string,
  'requirements' : string,
  'stipend' : string,
  'applicationLink' : string,
}
export type InternshipId = bigint;
export interface Job {
  'id' : JobId,
  'postedDate' : Timestamp,
  'role' : string,
  'description' : string,
  'deadline' : string,
  'isActive' : boolean,
  'eligibility' : string,
  'company' : string,
  'pdfKey' : string,
}
export type JobId = bigint;
export interface Note {
  'id' : NoteId,
  'title' : string,
  'subject' : string,
  'description' : string,
  'fileType' : FileType,
  'uploadDate' : Timestamp,
  'uploadedBy' : Principal,
  'fileKey' : string,
}
export type NoteId = bigint;
export interface Profile {
  'principal' : Principal,
  'semester' : bigint,
  'name' : string,
  'year' : bigint,
  'email' : string,
  'rollNumber' : string,
  'enrollmentDate' : Timestamp,
  'phone' : string,
  'course' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addInternship' : ActorMethod<
    [
      {
        'duration' : string,
        'role' : string,
        'description' : string,
        'deadline' : string,
        'company' : string,
        'pdfKey' : string,
        'requirements' : string,
        'stipend' : string,
        'applicationLink' : string,
      },
    ],
    bigint
  >,
  'addJob' : ActorMethod<
    [
      {
        'role' : string,
        'description' : string,
        'deadline' : string,
        'eligibility' : string,
        'company' : string,
        'pdfKey' : string,
      },
    ],
    bigint
  >,
  'addNote' : ActorMethod<
    [
      {
        'title' : string,
        'subject' : string,
        'description' : string,
        'fileType' : FileType,
        'fileKey' : string,
      },
    ],
    bigint
  >,
  'deleteInternship' : ActorMethod<[InternshipId], boolean>,
  'deleteJob' : ActorMethod<[JobId], boolean>,
  'deleteNote' : ActorMethod<[NoteId], boolean>,
  'getInternshipById' : ActorMethod<[InternshipId], [] | [Internship]>,
  'getInternships' : ActorMethod<[], Array<Internship>>,
  'getJobById' : ActorMethod<[JobId], [] | [Job]>,
  'getJobs' : ActorMethod<[], Array<Job>>,
  'getMyProfile' : ActorMethod<[], Profile>,
  'getNoteById' : ActorMethod<[NoteId], [] | [Note]>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getStudentProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listStudents' : ActorMethod<[], Array<Profile>>,
  'updateInternship' : ActorMethod<
    [
      InternshipId,
      {
        'duration' : string,
        'role' : string,
        'description' : string,
        'deadline' : string,
        'company' : string,
        'pdfKey' : string,
        'requirements' : string,
        'stipend' : string,
        'applicationLink' : string,
      },
    ],
    boolean
  >,
  'updateJob' : ActorMethod<
    [
      JobId,
      {
        'role' : string,
        'description' : string,
        'deadline' : string,
        'eligibility' : string,
        'company' : string,
        'pdfKey' : string,
      },
    ],
    boolean
  >,
  'updateMyProfile' : ActorMethod<
    [
      {
        'semester' : bigint,
        'name' : string,
        'year' : bigint,
        'email' : string,
        'rollNumber' : string,
        'phone' : string,
        'course' : string,
      },
    ],
    undefined
  >,
  'updateNote' : ActorMethod<
    [
      NoteId,
      {
        'title' : string,
        'subject' : string,
        'description' : string,
        'fileType' : FileType,
        'fileKey' : string,
      },
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];