/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FileType = IDL.Variant({ 'pdf' : IDL.Null, 'text' : IDL.Null });
export const InternshipId = IDL.Nat;
export const JobId = IDL.Nat;
export const NoteId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Internship = IDL.Record({
  'id' : InternshipId,
  'duration' : IDL.Text,
  'postedDate' : Timestamp,
  'role' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'pdfKey' : IDL.Text,
  'requirements' : IDL.Text,
  'stipend' : IDL.Text,
  'applicationLink' : IDL.Text,
});
export const Job = IDL.Record({
  'id' : JobId,
  'postedDate' : Timestamp,
  'role' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'isActive' : IDL.Bool,
  'eligibility' : IDL.Text,
  'company' : IDL.Text,
  'pdfKey' : IDL.Text,
});
export const Profile = IDL.Record({
  'principal' : IDL.Principal,
  'semester' : IDL.Nat,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
  'rollNumber' : IDL.Text,
  'enrollmentDate' : Timestamp,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'fileType' : FileType,
  'uploadDate' : Timestamp,
  'uploadedBy' : IDL.Principal,
  'fileKey' : IDL.Text,
});

export const idlService = IDL.Service({
  'addInternship' : IDL.Func(
      [
        IDL.Record({
          'duration' : IDL.Text,
          'role' : IDL.Text,
          'description' : IDL.Text,
          'deadline' : IDL.Text,
          'company' : IDL.Text,
          'pdfKey' : IDL.Text,
          'requirements' : IDL.Text,
          'stipend' : IDL.Text,
          'applicationLink' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'addJob' : IDL.Func(
      [
        IDL.Record({
          'role' : IDL.Text,
          'description' : IDL.Text,
          'deadline' : IDL.Text,
          'eligibility' : IDL.Text,
          'company' : IDL.Text,
          'pdfKey' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'addNote' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'subject' : IDL.Text,
          'description' : IDL.Text,
          'fileType' : FileType,
          'fileKey' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteInternship' : IDL.Func([InternshipId], [IDL.Bool], []),
  'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
  'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'getInternshipById' : IDL.Func(
      [InternshipId],
      [IDL.Opt(Internship)],
      ['query'],
    ),
  'getInternships' : IDL.Func([], [IDL.Vec(Internship)], ['query']),
  'getJobById' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getMyProfile' : IDL.Func([], [Profile], ['query']),
  'getNoteById' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getStudentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Profile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'updateInternship' : IDL.Func(
      [
        InternshipId,
        IDL.Record({
          'duration' : IDL.Text,
          'role' : IDL.Text,
          'description' : IDL.Text,
          'deadline' : IDL.Text,
          'company' : IDL.Text,
          'pdfKey' : IDL.Text,
          'requirements' : IDL.Text,
          'stipend' : IDL.Text,
          'applicationLink' : IDL.Text,
        }),
      ],
      [IDL.Bool],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        JobId,
        IDL.Record({
          'role' : IDL.Text,
          'description' : IDL.Text,
          'deadline' : IDL.Text,
          'eligibility' : IDL.Text,
          'company' : IDL.Text,
          'pdfKey' : IDL.Text,
        }),
      ],
      [IDL.Bool],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [
        IDL.Record({
          'semester' : IDL.Nat,
          'name' : IDL.Text,
          'year' : IDL.Nat,
          'email' : IDL.Text,
          'rollNumber' : IDL.Text,
          'phone' : IDL.Text,
          'course' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'updateNote' : IDL.Func(
      [
        NoteId,
        IDL.Record({
          'title' : IDL.Text,
          'subject' : IDL.Text,
          'description' : IDL.Text,
          'fileType' : FileType,
          'fileKey' : IDL.Text,
        }),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FileType = IDL.Variant({ 'pdf' : IDL.Null, 'text' : IDL.Null });
  const InternshipId = IDL.Nat;
  const JobId = IDL.Nat;
  const NoteId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Internship = IDL.Record({
    'id' : InternshipId,
    'duration' : IDL.Text,
    'postedDate' : Timestamp,
    'role' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'pdfKey' : IDL.Text,
    'requirements' : IDL.Text,
    'stipend' : IDL.Text,
    'applicationLink' : IDL.Text,
  });
  const Job = IDL.Record({
    'id' : JobId,
    'postedDate' : Timestamp,
    'role' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'isActive' : IDL.Bool,
    'eligibility' : IDL.Text,
    'company' : IDL.Text,
    'pdfKey' : IDL.Text,
  });
  const Profile = IDL.Record({
    'principal' : IDL.Principal,
    'semester' : IDL.Nat,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
    'rollNumber' : IDL.Text,
    'enrollmentDate' : Timestamp,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'fileType' : FileType,
    'uploadDate' : Timestamp,
    'uploadedBy' : IDL.Principal,
    'fileKey' : IDL.Text,
  });
  
  return IDL.Service({
    'addInternship' : IDL.Func(
        [
          IDL.Record({
            'duration' : IDL.Text,
            'role' : IDL.Text,
            'description' : IDL.Text,
            'deadline' : IDL.Text,
            'company' : IDL.Text,
            'pdfKey' : IDL.Text,
            'requirements' : IDL.Text,
            'stipend' : IDL.Text,
            'applicationLink' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'addJob' : IDL.Func(
        [
          IDL.Record({
            'role' : IDL.Text,
            'description' : IDL.Text,
            'deadline' : IDL.Text,
            'eligibility' : IDL.Text,
            'company' : IDL.Text,
            'pdfKey' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'addNote' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'subject' : IDL.Text,
            'description' : IDL.Text,
            'fileType' : FileType,
            'fileKey' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteInternship' : IDL.Func([InternshipId], [IDL.Bool], []),
    'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
    'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'getInternshipById' : IDL.Func(
        [InternshipId],
        [IDL.Opt(Internship)],
        ['query'],
      ),
    'getInternships' : IDL.Func([], [IDL.Vec(Internship)], ['query']),
    'getJobById' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getMyProfile' : IDL.Func([], [Profile], ['query']),
    'getNoteById' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Profile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'updateInternship' : IDL.Func(
        [
          InternshipId,
          IDL.Record({
            'duration' : IDL.Text,
            'role' : IDL.Text,
            'description' : IDL.Text,
            'deadline' : IDL.Text,
            'company' : IDL.Text,
            'pdfKey' : IDL.Text,
            'requirements' : IDL.Text,
            'stipend' : IDL.Text,
            'applicationLink' : IDL.Text,
          }),
        ],
        [IDL.Bool],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          JobId,
          IDL.Record({
            'role' : IDL.Text,
            'description' : IDL.Text,
            'deadline' : IDL.Text,
            'eligibility' : IDL.Text,
            'company' : IDL.Text,
            'pdfKey' : IDL.Text,
          }),
        ],
        [IDL.Bool],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [
          IDL.Record({
            'semester' : IDL.Nat,
            'name' : IDL.Text,
            'year' : IDL.Nat,
            'email' : IDL.Text,
            'rollNumber' : IDL.Text,
            'phone' : IDL.Text,
            'course' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'updateNote' : IDL.Func(
        [
          NoteId,
          IDL.Record({
            'title' : IDL.Text,
            'subject' : IDL.Text,
            'description' : IDL.Text,
            'fileType' : FileType,
            'fileKey' : IDL.Text,
          }),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };