/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type NoteId = bigint;
export type Timestamp = bigint;
export interface Job {
    id: JobId;
    postedDate: Timestamp;
    role: string;
    description: string;
    deadline: string;
    isActive: boolean;
    eligibility: string;
    company: string;
    pdfKey: string;
}
export type InternshipId = bigint;
export interface Internship {
    id: InternshipId;
    duration: string;
    postedDate: Timestamp;
    role: string;
    description: string;
    deadline: string;
    isActive: boolean;
    company: string;
    pdfKey: string;
    requirements: string;
    stipend: string;
    applicationLink: string;
}
export type JobId = bigint;
export interface Profile {
    principal: Principal;
    semester: bigint;
    name: string;
    year: bigint;
    email: string;
    rollNumber: string;
    enrollmentDate: Timestamp;
    phone: string;
    course: string;
}
export interface Note {
    id: NoteId;
    title: string;
    subject: string;
    description: string;
    fileType: FileType;
    uploadDate: Timestamp;
    uploadedBy: Principal;
    fileKey: string;
}
export enum FileType {
    pdf = "pdf",
    text = "text"
}
export interface backendInterface {
    addInternship(input: {
        duration: string;
        role: string;
        description: string;
        deadline: string;
        company: string;
        pdfKey: string;
        requirements: string;
        stipend: string;
        applicationLink: string;
    }): Promise<bigint>;
    addJob(input: {
        role: string;
        description: string;
        deadline: string;
        eligibility: string;
        company: string;
        pdfKey: string;
    }): Promise<bigint>;
    addNote(input: {
        title: string;
        subject: string;
        description: string;
        fileType: FileType;
        fileKey: string;
    }): Promise<bigint>;
    deleteInternship(id: InternshipId): Promise<boolean>;
    deleteJob(id: JobId): Promise<boolean>;
    deleteNote(id: NoteId): Promise<boolean>;
    getInternshipById(id: InternshipId): Promise<Internship | null>;
    getInternships(): Promise<Array<Internship>>;
    getJobById(id: JobId): Promise<Job | null>;
    getJobs(): Promise<Array<Job>>;
    getMyProfile(): Promise<Profile>;
    getNoteById(id: NoteId): Promise<Note | null>;
    getNotes(): Promise<Array<Note>>;
    getStudentProfile(p: Principal): Promise<Profile | null>;
    isAdmin(): Promise<boolean>;
    listStudents(): Promise<Array<Profile>>;
    updateInternship(id: InternshipId, input: {
        duration: string;
        role: string;
        description: string;
        deadline: string;
        company: string;
        pdfKey: string;
        requirements: string;
        stipend: string;
        applicationLink: string;
    }): Promise<boolean>;
    updateJob(id: JobId, input: {
        role: string;
        description: string;
        deadline: string;
        eligibility: string;
        company: string;
        pdfKey: string;
    }): Promise<boolean>;
    updateMyProfile(input: {
        semester: bigint;
        name: string;
        year: bigint;
        email: string;
        rollNumber: string;
        phone: string;
        course: string;
    }): Promise<void>;
    updateNote(id: NoteId, input: {
        title: string;
        subject: string;
        description: string;
        fileType: FileType;
        fileKey: string;
    }): Promise<boolean>;
}
import type { FileType as _FileType, Internship as _Internship, Job as _Job, Note as _Note, NoteId as _NoteId, Profile as _Profile, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addInternship(arg0: {
        duration: string;
        role: string;
        description: string;
        deadline: string;
        company: string;
        pdfKey: string;
        requirements: string;
        stipend: string;
        applicationLink: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInternship(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInternship(arg0);
            return result;
        }
    }
    async addJob(arg0: {
        role: string;
        description: string;
        deadline: string;
        eligibility: string;
        company: string;
        pdfKey: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0);
            return result;
        }
    }
    async addNote(arg0: {
        title: string;
        subject: string;
        description: string;
        fileType: FileType;
        fileKey: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteInternship(arg0: InternshipId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInternship(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInternship(arg0);
            return result;
        }
    }
    async deleteJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteNote(arg0: NoteId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getInternshipById(arg0: InternshipId): Promise<Internship | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInternshipById(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInternshipById(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInternships(): Promise<Array<Internship>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInternships();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInternships();
            return result;
        }
    }
    async getJobById(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobById(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobById(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobs();
            return result;
        }
    }
    async getMyProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getNoteById(arg0: NoteId): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async listStudents(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return result;
        }
    }
    async updateInternship(arg0: InternshipId, arg1: {
        duration: string;
        role: string;
        description: string;
        deadline: string;
        company: string;
        pdfKey: string;
        requirements: string;
        stipend: string;
        applicationLink: string;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInternship(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInternship(arg0, arg1);
            return result;
        }
    }
    async updateJob(arg0: JobId, arg1: {
        role: string;
        description: string;
        deadline: string;
        eligibility: string;
        company: string;
        pdfKey: string;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1);
            return result;
        }
    }
    async updateMyProfile(arg0: {
        semester: bigint;
        name: string;
        year: bigint;
        email: string;
        rollNumber: string;
        phone: string;
        course: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0);
            return result;
        }
    }
    async updateNote(arg0: NoteId, arg1: {
        title: string;
        subject: string;
        description: string;
        fileType: FileType;
        fileKey: string;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, to_candid_record_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, to_candid_record_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_FileType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Internship]): Internship | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoteId;
    title: string;
    subject: string;
    description: string;
    fileType: _FileType;
    uploadDate: _Timestamp;
    uploadedBy: Principal;
    fileKey: string;
}): {
    id: NoteId;
    title: string;
    subject: string;
    description: string;
    fileType: FileType;
    uploadDate: Timestamp;
    uploadedBy: Principal;
    fileKey: string;
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        description: value.description,
        fileType: from_candid_FileType_n9(_uploadFile, _downloadFile, value.fileType),
        uploadDate: value.uploadDate,
        uploadedBy: value.uploadedBy,
        fileKey: value.fileKey
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    text: null;
}): FileType {
    return "pdf" in value ? FileType.pdf : "text" in value ? FileType.text : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n7(_uploadFile, _downloadFile, x));
}
function to_candid_FileType_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subject: string;
    description: string;
    fileType: FileType;
    fileKey: string;
}): {
    title: string;
    subject: string;
    description: string;
    fileType: _FileType;
    fileKey: string;
} {
    return {
        title: value.title,
        subject: value.subject,
        description: value.description,
        fileType: to_candid_FileType_n2(_uploadFile, _downloadFile, value.fileType),
        fileKey: value.fileKey
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    pdf: null;
} | {
    text: null;
} {
    return value == FileType.pdf ? {
        pdf: null
    } : value == FileType.text ? {
        text: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
